server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://wolf:cloud@ek-server.com:1111/eureka/

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      # 路由网关自动创建路由配置
#      discovery:
#        locator:
#          enabled: true
      routes:
        - id: hello-route
          uri: lb://hello-service
          predicates:
            - Path=/demo/**
#            - Method=GET,POST
          filters:
            - StripPrefix=1

        - id: didi-route
          uri: lb://didispace
          predicates:
            - Path=/didi/**
          filters:
            - StripPrefix=1
# 展示所以的路由节点信息
management:
  endpoints:
    web:
      exposure:
        include: "*"


# 配置日志级别，方便调试
logging:
  level:
    org.springframework.cloud.gateway: debug