server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://wolf:cloud@ek-server.com:1111/eureka/
#    enabled: true

spring:
  application:
    # 应用名称
    name: spring-cloud-gateway
  cloud:
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: HELLO-SERVICE-route
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://hello-service
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Path=/demo/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
        - id: DIDISPACE—route
          uri: lb://didispace
          predicates:
            - Method=GET,POST
            - Path=/didi/**
          filters:
            - StripPrefix=1

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug